version: '3.8'

services:
  frontend:
    image: therealrustam/foodgram_front:v14.04.2022
    volumes:
      - ../frontend/:/app/result_build/

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - '80:80'
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/staticfiles/
      - media_value:/var/html/media/
    depends_on:
      - backend

  db:
    env_file:
      - .env
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always

  backend:
    image: therealrustam/foodgram:latest
    restart: always
    depends_on:
      - db
    volumes:
      - static_value:/code/staticfiles/
      - media_value:/code/media/
    env_file:
      - ./.env

volumes:

  result_build:
  postgres_data:
  static_value:
  media_value:
