# Generated by Django 2.2.19 on 2022-03-27 08:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0003_auto_20220327_1319'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FavoriteR',
            new_name='Favorite',
        ),
    ]
