# Generated by Django 2.2.19 on 2022-04-10 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20220410_1137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='recipes',
            new_name='recipe',
        ),
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='unique_cart'),
        ),
    ]
